config/routes.rb
SecureWiki::Application.routes.draw do
  resources :pages, :only => [:index, :new, :create]
  # root :to => "home#index"

  devise_for :users
  resources :users, :only => [:index, :show]

  root :to => "pages#show", id: 'home'

  match ':id(.:format)/new' => "pages#new", as: :new, via: :get
  match ':id(.:format)/edit' => "pages#edit", as: :edit_page, via: :get
  match ':id(.:format)' => "pages#show", as: :page, via: :get
  match ':id(.:format)' => "pages#update", via: :put
  match ':id(.:format)' => "pages#create", via: :post
  match ':id(.:format)' => "pages#destroy", via: :delete

end

app/models/page.rb
class Page
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Versioning
  include Mongoid::Timestamps
  field :name, :type => String
  field :content, :type => String, :default => ''
  field :html, :type => String, :default => ''
  key :name
  validate :name, presence: true, length: { max: 80, min: 2 }
  before_save :encode_html

  def encode_html
    self.html = RDiscount.new(content, :autolink, :smart).to_html
#    RedCloth.new(content).to_html
  end
  def to_s
    (name || '').to_s.titleize
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, :except => [:index, :show]
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html, :json
  before_filter :get_page, only: [:show, :edit, :update, :destroy]
  before_filter :new_page, only: [:new, :create]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
    respond_with @pages
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    respond_with @page
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    respond_with @page
  end

  # GET /pages/1/edit
  def edit
    respond_with @page
  end

  # POST /pages
  # POST /pages.json
  def create
    @page.save
    respond_with @page
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page.update_attributes(params[:page])
    respond_with @page
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_with @page
  end

protected
  def get_page
    id = params[:id] 
    @page = Page.find(id)
  rescue
    if id == 'home'
      @page = Page.create name: id
    else
      redirect_to new_path(@page)
    end
  end
  def new_page
    page = params[:page] || {}
    id = params[:id]
    if id
      page[:name] ||= id
    end
    @page = Page.new(page)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
      @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 Home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Securewiki
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body{:class => params[:controller]}
    #container.container
      %header
        = link_to image_tag("/logo.png"), root_path, :class => 'logo'
        %nav
          = render 'shared/navigation'
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_\#{name}" if msg.is_a?(String)
      #main{:role => "main"}
        = yield
      %footer
        = render 'shared/footer'

app/views/pages/_form.html.haml
= form_for @page do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit 'Save'
  .field
    = f.label :name
    = f.text_field :name, class: :name
  .field
    = f.label :content
    = f.text_area :content

app/views/pages/edit.html.haml
%h1 Editing page #{@page}
= render 'form'

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Name
    %th Created
    %th Updated
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= link_to page, page

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page #{@page}
= render 'form'

app/views/pages/show.html.haml
%h1= @page
=raw @page.html

app/views/shared/_footer.html.haml
%nav
  %ul
    %li 
      %a{href:'https://github.com/capnregex/secure_wiki'} Secure Wiki
    - if @page
      %li page version #{@page.version}
      %li last updated at #{@page.updated_at}

app/views/shared/_navigation.html.haml
%ul.user_menu
  - if user_signed_in?
    %li= link_to(current_user.name, user_path(current_user))
    %li= link_to('Profile', edit_user_registration_path)
    %li= link_to('Users', users_path)
    %li= link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li= link_to('Login', new_user_session_path)
    %li= link_to('Sign up', new_user_registration_path)
%ul.page_menu
  %li= link_to 'Pages', pages_path
  - if @page and @page.persisted?
    %li= link_to 'Show', @page
    %li= link_to 'Edit', edit_page_path(@page)
    %li= link_to 'Destroy', @page, :confirm => 'Are you sure?', :method => :delete
  %li= link_to 'New', new_page_path
%ul.hmenu
  %li= link_to 'Home', root_path
%h1.title Securewiki

app/views/users/index.html.haml
%h3 Users
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}